version: '3'
services:

  book-catalog:
    image: book-catalog
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
      - "8081:8081"
    environment:
      - PORT=8088
      - DATABASE_URL=postgresql://arslan_moosa_db_7_2_part3_user:fsF9O0hukPG4umN40LEQpq3eqGml62Jk@dpg-crm61md6l47c738uaq10-a.oregon-postgres.render.com/arslan_moosa_db_7_2_part3
    restart: "no"

  inventory-management:
    image: inventory-management
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
     - "8082:8082"
    environment:
      - PORT=8089
      - DATABASE_URL=postgresql://arslan_moosa_db_7_2_part3_user:fsF9O0hukPG4umN40LEQpq3eqGml62Jk@dpg-crm61md6l47c738uaq10-a.oregon-postgres.render.com/arslan_moosa_db_7_2_part3
    restart: "no"