apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: amcon.azurecr.io/books:latest
        env:
        - name: PORT
          value: "8088"
        - name: DATABASE_URL
          value: "postgresql://arslan_moosa_db_7_2_part3_user:fsF9O0hukPG4umN40LEQpq3eqGml62Jk@dpg-crm61md6l47c738uaq10-a.oregon-postgres.render.com/arslan_moosa_db_7_2_part3"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management
        image: amcon.azurecr.io/inventory:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        env:
        - name: PORT
          value: "8082"
        - name: DATABASE_URL
          value: "postgresql://arslan_moosa_db_7_2_part3_user:fsF9O0hukPG4umN40LEQpq3eqGml62Jk@dpg-crm61md6l47c738uaq10-a.oregon-postgres.render.com/arslan_moosa_db_7_2_part3"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management
spec:
  selector:
    app: inventory-management
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8082